cat mysql-db-deployment-withrolling.yaml
--- 

apiVersion: apps/v1

kind: Deployment

metadata: 

  labels: 

    environment: dev-mysql-db

  name: dev-mysql-db

spec: 

  minReadySeconds: 10

  replicas: 1

  selector: 

    matchLabels: 

      environment: dev-mysql-db

  strategy: 

    rollingUpdate: 

      maxSurge: 1

      maxUnavailable: 0

    type: RollingUpdate

  template: 

    metadata: 

      labels: 

        environment: dev-mysql-db

    spec: 

      containers: 

        - 

          env: 

          image: "mysql:8.0.23"

          name: mysql-db

        - 

          name: MYSQL_ROOT_PASSWORD

          valueFrom: 

            secretKeyRef: 

              key: password

              name: db-root-credentials

        - 

          name: MYSQL_USER

          valueFrom: 

            secretKeyRef: 

              key: username

              name: db-credentials

        - 

          name: MYSQL_PASSWORD

          valueFrom: 

            secretKeyRef: 

              key: password

              name: db-credentials

        - 

          name: MYSQL_DATABASE

          ports: 

            - 

              containerPort: 3306

          valueFrom: 

            configMapKeyRef: 

              key: name

              name: db-conf

          volumeMounts: 

        - 

          mountPath: /var/lib/mysql

          name: mysql-persistent-storage

      nodeName: node3

      volumes: 

        - 

          name: mysql-persistent-storage

          persistentVolumeClaim: 

            claimName: mysql-pv-claim
