apiVersion: v1
kind: Secret
metadata:
  name: %ENVIRONMENT%-%APP_NAME%-credentials
  namespace: %NAMESPACE%
data:
 username: %SERVICE_SECRET_USER% #bW9uZ28tc3Zj
 password: %SERVICE_SECRET% #bW9uZ28tc3ZjQG1vbmdv